language: node_js
node_js:
- "stable"
cache:
  directories:
  - "node_modules"
jobs:
  include:
  - stage: install
    script: npm i
  - stage: build
    script: npm build
  - stage: test
    script: npm test